# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a9c3fdb6fa70ca94b5fcf442b86c6721b192064c48362cf93a78c1ab8f13db37e2bdb4acf8f5f7f680fd27d6802530e5f7638fc701d4decb0b2ab0a3a2f2f01

test:
  secret_key_base: 5e442ec946b32728162d0d4f85a86cee2f181d80f3d4acec58782c962189570292b83e79dbf070a65d38e09f6842f0ebbcfa3bd3328c5db72b7f712308552f26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
